#!/usr/bin/env python

"""
Name: pre-commit(.py)
Author: Connor Youngs
Description: A Python script to test the different environment variables passed by and the behaviour of the pre-commit githook.
Date:28/12/2020

To use Move this file into the .git/hooks/ folder of the top level working directory of a git repository.
Ensure it can be executed and is called "pre-commit" and then run the git commit command.
"""
import os 
import sys

print(os.getcwd()) #Prints the current working directory, the pre-commit hook uses the top level of the repo working tree.
print(os.environ['GIT_AUTHOR_NAME']) #Should be automatically set to .git
print(os.environ['GIT_INDEX_FILE']) #Should be automatically set to .git/index/
print(os.environ['GIT_AUTHOR_DATE'])
sys.exit(1) #This prevents the git commit command from continuing, returning zero would indicate success and allow git commit to continue.

